<h3>Thời tiết trong ngày</h3>

<div id="weather">
    <div class="top-content">
        <h2>Hà Nội, Việt Nam</h2>
    </div>

    <div class="mid-content">
        <div class="col">
            <div class="image"></div>
            <div class="temperature"></div>
        </div>
        <div class="col">
            <ul class="info"></ul>
        </div>
    </div>

    <div class="forecast">

    </div>
</div>

<script>
    require(['jquery', 'simple_weather'], function ($) {
        $(function () {
            $.simpleWeather({
                location: 'Hanoi, VN',
                woeid: '',
                unit: 'c',
                success: function (weather) {
                    $('.image').html('<img src="' + weather.image + '"/>');
                    $('.temperature').html(weather.temp + '<sup>o</sup>C');
                    var info = '<li>Status: ' + weather.currently + '</li>' +
                        '<li>Range: ' + weather.low + '<sup>o</sup>C - ' + weather.high + '<sup>o</sup>C</li>' +
                        '<li>Wind: ' + weather.wind.speed + ' km/h</li>';

                    $('.info').html(info);

                    // Add forecast informations
                    var forecast = '<h3>Dự báo thời tiết</h3>';
                    for(var i=0;i<weather.forecast.length;i++) {
                        forecast += '<p>'+weather.forecast[i].day+': '+weather.forecast[i].high+'<sup>o</sup>C</p>';
                    }
                    $('.forecast').html(forecast);

                },
                error: function (error) {
                    $("#weather").html('<p>' + error + '</p>');
                }
            });
        });
    });
</script>